### ISSUE TITLE
Checkov fails with Python 3.10

### ISSUE THREAD

**Issue by ndegory** [bridgecrewio/checkov#1721]
**Describe the bug**

Checkov errors with Python 3.10 with the backtrace below:
```
    from checkov.main import run
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 23, in <module>
    from checkov.common.runners.runner_registry import RunnerRegistry, OUTPUT_CHOICES
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 18, in <module>
    from checkov.terraform.runner import Runner as tf_runner
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/runner.py", line 29, in <module>
    from checkov.terraform.graph_builder.local_graph import TerraformLocalGraph
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/local_graph.py", line 26, in <module>
    from checkov.terraform.graph_builder.variable_rendering.renderer import TerraformVariableRenderer
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 2, in <module>
    from collections import Hashable
ImportError: cannot import name 'Hashable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

**To Reproduce**

1. build an image with checkov and Python 3.10

```
❯ cat Dockerfile
FROM python:3.10-alpine
RUN apk add --no-cache git util-linux
RUN python3 -m pip install --no-cache-dir -U checkov
CMD ["checkov", "--directory", "/home"]
```

2. build the image

```
❯ docker build -f Dockerfile -t checkov:latest .
[+] Building 47.3s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 203B                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/python:3.10-alpine                                                                                                           2.7s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                   0.0s
 => [1/3] FROM docker.io/library/python:3.10-alpine@sha256:9bcb35b60414ecd43a289955480514fa305b7598d2a8d2ec622e812dda6418e3                                                     0.1s
 => => resolve docker.io/library/python:3.10-alpine@sha256:9bcb35b60414ecd43a289955480514fa305b7598d2a8d2ec622e812dda6418e3                                                     0.0s
 => [2/3] RUN apk add --no-cache git util-linux                                                                                                                                 4.6s
 => [3/3] RUN python3 -m pip install --no-cache-dir -U checkov                                                                                                                 38.7s
 => exporting to image                                                                                                                                                          1.1s
 => => exporting layers                                                                                                                                                         1.1s
 => => writing image sha256:0df1ea88e002a544a767379e89ccfaac2a0f34f4a4f7b9a9dbdc6815b4ba6f2e                                                                                    0.0s
 => => naming to docker.io/library/checkov:latest                                                                                                                               0.0s
```

3. Run checkov in the container

```
❯ docker run --rm checkov:latest
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 23, in <module>
    from checkov.common.runners.runner_registry import RunnerRegistry, OUTPUT_CHOICES
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 18, in <module>
    from checkov.terraform.runner import Runner as tf_runner
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/runner.py", line 29, in <module>
    from checkov.terraform.graph_builder.local_graph import TerraformLocalGraph
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/local_graph.py", line 26, in <module>
    from checkov.terraform.graph_builder.variable_rendering.renderer import TerraformVariableRenderer
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 2, in <module>
    from collections import Hashable
ImportError: cannot import name 'Hashable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

**Expected behavior**

Shouldn't fail.
Changing the base image to python:3.7-alpine 

```
2021-10-06 23:12:27,226 [MainThread  ] [WARNI]  The json runner requires that external checks are defined.

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.476
```

**Desktop (please complete the following information):**
 - OS: container alpine 3.14.2
 - Checkov Version 2.0.476

**Additional context**

Seems to be an easy fix, that would work with Python 3.3 and upwards:
```
❯ python3
Python 3.9.7 (default, Sep  3 2021, 12:37:55)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Hashable
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
>>>
```

**Comment by gruebel** [comment]
this was fixed with #1742
