### ISSUE TITLE
ImportError: cannot import name util

### ISSUE THREAD

**Issue by jwcmd** [bridgecrewio/checkov#739]
**Describe the bug**
Following the installation instructions does not succeed on Debian Stable (buster).

**To Reproduce**
1. Run cli command 'pip install checkov'

```
root@buster:~# pip install checkov
Collecting checkov
  Downloading https://files.pythonhosted.org/packages/8f/cc/f3f488215771f2f81a10a5c256be1e49860c16bd74e72bcaa4df10bed84d/checkov-1.0.669.tar.gz (153kB)
    100% |████████████████████████████████| 153kB 2.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-DJZ3d5/checkov/setup.py", line 4, in <module>
        from importlib import util
    ImportError: cannot import name util

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-DJZ3d5/checkov/
```

**Expected behavior**
The installation instructions should work on Debian Stable.

**Screenshots**

**Desktop (please complete the following information):**
```
root@buster:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Additional context**

**Comment by KevinHock** [comment]
Nice cookie @jwcmd 🍪

**Comment by jwcmd** [comment]
It's a cinnamon-bun Oreo! Would recommend lol

**Comment by schosterbarak** [comment]
@jwcmd can you try with pip3? and share the pip version

**Comment by metahertz** [comment]
Hey @jwcmd I'm also wondering if the version of pip you're running is for py2.7,
Could you try `pip3 install checkov` or even `python3 -m pip install checkov`.

Linux desktop user by the way? :)

**Comment by ckea** [comment]
I had this exact issue, I was using
pip 19.0.3 from /usr/local/homebrew/lib/python2.7/site-packages/pip (python 2.7)

and saw

```
$ pip install checkov
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting checkov
  Using cached https://files.pythonhosted.org/packages/8f/cc/f3f488215771f2f81a10a5c256be1e49860c16bd74e72bcaa4df10bed84d/checkov-1.0.669.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4g/45qzrtts5nq587n5wkcz5gf4jwhpzz/T/pip-install-eLwvl3/checkov/setup.py", line 4, in <module>
        from importlib import util
    ImportError: cannot import name util

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4g/45qzrtts5nq587n5wkcz5gf4jwhpzz/T/pip-install-eLwvl3/checkov/
```

Using pip3 there was no issue.

**Comment by larryboymi** [comment]
Had the same issue with 2.7 & pip

**Comment by schosterbarak** [comment]
@ckea @larryboymi checkov works with python 3.7 and above. it will not work with 2.7

**Comment by larryboymi** [comment]
I think I could install some older versions but none of the new. Thanks!
